In [2]:
import pandas as pd
import numpy as np

In [4]:
#读取数据
path='breast-cancer-wisconsin.data'
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape','Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin','Normal Nucleoli', 'Mitoses', 'Class']
data=pd.read_csv(path,names=column_name)

In [6]:
data

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
694              776715                3                        1   
695              841769                2                        1   
696              888820                5                       10   
697              897471                4                        8   
698              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
694                         1                  1                            3   
695                         1                  1                            2   
696                        10                  3                            7   
697                         6                  4                            3   
698                         8                  5                            4   

    Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0             1                3                1        1      2  
1            10                3                2        1      2  
2             2                3                1        1      2  
3             4                3                7        1      2  
4             1                3                1        1      2  
..          ...              ...              ...      ...    ...  
694           2                1                1        1      2  
695           1                1                1        1      2  
696           3                8               10        2      4  
697           4               10                6        1      4  
698           5               10                4        1      4  

[699 rows x 11 columns]

In [7]:
# 2、缺失值处理
# 1）替换->np.nan
data = data.replace(to_replace='?',value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

In [9]:
data.isnull().any() #不存在缺失值

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [10]:
# 3、划分数据集
from sklearn.model_selection import train_test_split

In [11]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [12]:
# 筛选特征值和目标值
x = data.iloc[:,1:-1]
y = data['Class']

In [13]:
x

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                  5                        1                         1   
1                  5                        4                         4   
2                  3                        1                         1   
3                  6                        8                         8   
4                  4                        1                         1   
..               ...                      ...                       ...   
694                3                        1                         1   
695                2                        1                         1   
696                5                       10                        10   
697                4                        8                         6   
698                4                        8                         8   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                    1                            2           1   
1                    5                            7          10   
2                    1                            2           2   
3                    1                            3           4   
4                    3                            2           1   
..                 ...                          ...         ...   
694                  1                            3           2   
695                  1                            2           1   
696                  3                            7           3   
697                  4                            3           4   
698                  5                            4           5   

     Bland Chromatin  Normal Nucleoli  Mitoses  
0                  3                1        1  
1                  3                2        1  
2                  3                1        1  
3                  3                7        1  
4                  3                1        1  
..               ...              ...      ...  
694                1                1        1  
695                1                1        1  
696                8               10        2  
697               10                6        1  
698               10                4        1  

[683 rows x 9 columns]

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [15]:
x_train.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
633                8                        7                         4   
78                 3                        1                         1   
295                5                        5                         7   
590                4                       10                         8   
303                1                        1                         1   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
633                  4                            5           3   
78                   1                            2           3   
295                  8                            6          10   
590                  5                            4           1   
303                  1                            2           1   

     Bland Chromatin  Normal Nucleoli  Mitoses  
633                5               10        1  
78                 3                1        1  
295                7                4        1  
590               10                1        1  
303                3                1        1

In [16]:
# 4、标准化
from sklearn.preprocessing import StandardScaler

In [17]:
transfer=StandardScaler()
x_train=transfer.fit_transform(x_train)
x_test=transfer.transform(x_test)

In [18]:
x_train

array([[ 1.25016359,  1.21009394,  0.22925768, ...,  0.60776127,
         2.22022275, -0.35911084],
       [-0.53379337, -0.71104745, -0.75712831, ..., -0.19526781,
        -0.62561492, -0.35911084],
       [ 0.17978941,  0.56971348,  1.21564367, ...,  1.41079035,
         0.32299763, -0.35911084],
       ...,
       [ 0.17978941, -0.39085722, -0.75712831, ..., -0.99829689,
        -0.62561492, -0.35911084],
       [-0.53379337, -0.07066698,  0.55805301, ...,  1.41079035,
        -0.62561492, -0.35911084],
       [ 0.53658081, -0.71104745, -0.75712831, ..., -0.59678235,
        -0.62561492, -0.35911084]])

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
# 5、预估器流程
estimator=LogisticRegression()
estimator.fit(x_train,y_train)

LogisticRegression()

In [21]:
# 逻辑回归参考模型：回归系数和偏置
estimator.coef_

array([[1.11276378, 0.23248923, 0.79683205, 0.51828937, 0.07873313,
        1.53180562, 0.98492773, 0.72662987, 0.92187856]])

In [22]:
estimator.intercept_

array([-0.88373588])

In [23]:
# 6、模型评估
#方法1：直接比对真实值和预测值
y_predict=estimator.predict(x_test)
print("y_predict:\n",y_predict)
print("直接比对真实值和预测值\n",y_test==y_predict)
#方法2：计算准确率
score=estimator.score(x_test,y_test)
print('准确率为\n',score)

y_predict:
 [2 2 2 4 2 4 4 2 2 4 4 4 2 4 4 2 2 4 2 4 2 2 2 4 2 4 2 2 2 2 2 4 2 4 2 2 4
 4 2 2 2 2 2 4 2 2 2 2 2 2 2 4 4 2 2 4 2 4 4 2 2 2 2 2 2 4 2 2 2 2 2 2 2 4
 2 2 4 2 2 4 4 2 4 2 2 2 2 2 2 4 4 4 2 2 2 4 4 2 2 2 4 4 2 2 2 4 2 2 2 2 4
 2 2 2 2 2 2 4 4 2 4 2 4 2 2 2 2 2 2 2 2 2 4 2 2 4 2 2 2 2 2 2 2 2 4 2 4 2
 4 2 4 4 2 2 4 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2]
直接比对真实值和预测值
 424     True
248     True
51     False
160     True
422     True
       ...  
630     True
687     True
170     True
335     True
22      True
Name: Class, Length: 171, dtype: bool
准确率为
 0.9649122807017544
